name: deploy

on:
  schedule:
    - cron: "30 06 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  ğŸš€
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Install pnpm  ğŸš€
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js  ğŸš€
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: pnpm

      - name: Install Deps  ğŸš€
        run: pnpm install

      - name: Build project  ğŸš€
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run build

      - name: copy README.md
        run: cp README.md docs/.vitepress/dist

      - name: Upload h7ml ğŸš€
        uses: actions/upload-artifact@v2
        with:
          name: h7ml
          path: docs/.vitepress/dist

      - name: Deploy to gh pages  ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: h7ml/h7ml
          branch: gh-pages
          folder: docs/.vitepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy to surge ğŸš€
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "better-ui.surge.sh"
          project: docs/.vitepress/dist
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

      - name: Deploy to gh-pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: better-ui/better-ui
          branch: gh-pages
          folder: docs/.vitepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}

  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee  ğŸš€
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:better-ui/better-ui.git
          destination-repo: git@gitee.com:better-ui/better-ui.git

      - name: Build Gitee Pages  ğŸš€
        uses: yanglbme/gitee-pages-action@main
        with:
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ç”¨æˆ·å
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          # æ³¨æ„åœ¨ Settings->Secrets é…ç½® GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ä»“åº“ï¼Œä»“åº“åä¸¥æ ¼åŒºåˆ†å¤§å°å†™ï¼Œè¯·å‡†ç¡®å¡«å†™ï¼Œå¦åˆ™ä¼šå‡ºé”™
          gitee-repo: better-ui/better-ui
          # è¦éƒ¨ç½²çš„åˆ†æ”¯ï¼Œé»˜è®¤æ˜¯ masterï¼Œè‹¥æ˜¯å…¶ä»–åˆ†æ”¯ï¼Œåˆ™éœ€è¦æŒ‡å®šï¼ˆæŒ‡å®šçš„åˆ†æ”¯å¿…é¡»å­˜åœ¨ï¼‰
          branch: gh-pages
    needs: deploy
