name: main
on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      root_sol:
        description: "Release Title"
        required: true
        default: "better-ui"
# è®¾ç½®ä¸Šæµ·æ—¶åŒº
env:
  TZ: Asia/Shanghai

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸš€
        uses: actions/checkout@v2
      - name: Sync better-ui ğŸš€
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/better-ui
          dst: gitee/better-ui
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          #          static_list: "better-ui"
          account_type: org
    needs: deploy

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  ğŸš€
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Install pnpm  ğŸš€
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js  ğŸš€
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: pnpm

      - name: Install Deps  ğŸš€
        run: pnpm install

      - name: Build project  ğŸš€
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          cd packages/better-ui
          pnpm run docs:build

      - name: copy README.md
        run: cp README.md packages/better-ui/docs/.vitepress/dist

      - name: Upload better-ui ğŸš€
        uses: actions/upload-artifact@v2
        with:
          name: better-ui
          path: packages/better-ui/docs/.vitepress/dist

      - name: Deploy to github gh-pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GIT_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/better-ui/docs/.vitepress/dist

      - name: Deploy to surge ğŸš€
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "better-ui.surge.sh"
          project: packages/better-ui/docs/.vitepress/dist
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

      - name: Deploy to gh-pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: better-ui/better-ui
          branch: gh-pages
          folder: packages/better-ui/docs/.vitepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy to better-ui pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: better-ui/better-ui.github.io
          branch: gh-pages
          folder: packages/better-ui/docs/.vitepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}

  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages  ğŸš€
        uses: yanglbme/gitee-pages-action@main
        with:
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ç”¨æˆ·å
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          # æ³¨æ„åœ¨ Settings->Secrets é…ç½® GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ä»“åº“ï¼Œä»“åº“åä¸¥æ ¼åŒºåˆ†å¤§å°å†™ï¼Œè¯·å‡†ç¡®å¡«å†™ï¼Œå¦åˆ™ä¼šå‡ºé”™
          gitee-repo: better-ui/better-ui
          # è¦éƒ¨ç½²çš„åˆ†æ”¯ï¼Œé»˜è®¤æ˜¯ masterï¼Œè‹¥æ˜¯å…¶ä»–åˆ†æ”¯ï¼Œåˆ™éœ€è¦æŒ‡å®šï¼ˆæŒ‡å®šçš„åˆ†æ”¯å¿…é¡»å­˜åœ¨ï¼‰
          branch: gh-pages
    needs: sync

  clear:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸš€
        uses: actions/checkout@v2
        with:
          repository: "jdsync/Workflows-Cleaner"
      - name: Set up Python ğŸš€
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install pipenv ğŸš€
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
          EXPIRE_TIME: "1h"
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv install
          pipenv run python run.py
      - name: Upload coverage to Codecov  ğŸš€
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
    needs: gh-pages
